FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish gpt.csproj -c Release -r linux-x64 -o /app/publish --self-contained true -p:PublishSingleFile=true

FROM redhat/ubi9
WORKDIR /app
RUN yum install -y libicu
COPY --from=build /app/publish .
COPY --from=build /src/appsettings.json .
ENV GPT__MODE="Discord"
ENV GPT__CHUNKSIZE="1536"
ENV GPT__MAXTOKENS="64000"
ENV GPT__MODEL="gpt-5.2"
ENTRYPOINT ./gpt
